// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
export interface User {
  readonly username: string; // key
  readonly name?: string;
  readonly lastname?: string;
  readonly phone?: string;
  readonly address?: string;
}