// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import { DynamoDB } from 'aws-sdk';
import { Project } from './model';
export class ProjectClient {
  readonly client = new DynamoDB();
  public async putItem(item: Project) {
    const attrs: DynamoDB.PutItemInputAttributeMap = {};
    attrs.pid = { S: item.pid };
    if (item.name != null) {
      attrs.name = { S: item.name };
    }
    if (item.description != null) {
      attrs.description = { S: item.description };
    }
    const req: DynamoDB.PutItemInput = {
      TableName: process.env.PROJECT_TABLE_NAME!,
      Item: attrs,
    };
    return this.client.putItem(req).promise();
  }
}